
init 10:
    $ espe_ambience_list = { }

    $ espe_ambience_list["Лодочная станция. День"] = ambience_boat_station_day
    $ espe_ambience_list["Лодочная станция. Ночь"] = ambience_boat_station_night
    $ espe_ambience_list["Площадь. День"] = ambience_camp_center_day
    $ espe_ambience_list["Площадь. Вечер"] = ambience_camp_center_evening
    $ espe_ambience_list["Площадь. Ночь"] = ambience_camp_center_night
    $ espe_ambience_list["Вход в лагерь. День"] = ambience_camp_entrance_day
    $ espe_ambience_list["Вход в лагерь. Людно. День"] = ambience_camp_entrance_day_people
    $ espe_ambience_list["Вход в лагерь. Вечер"] = ambience_camp_entrance_evening
    $ espe_ambience_list["Вход в лагерь. Ночь"] = ambience_camp_entrance_night
    $ espe_ambience_list["Катакомбы"] = ambience_catacombs
    $ espe_ambience_list["Катакомбы. Камушки"] = ambience_catacombs_stones
    $ espe_ambience_list["Клубы. Внутри. День"] = ambience_clubs_inside_day
    $ espe_ambience_list["Ветер"] = ambience_cold_wind_loop
    $ espe_ambience_list["Шум птиц"] = ambience_day_countryside_ambience
    $ espe_ambience_list["Столовая. Пустая"] = ambience_dining_hall_empty
    $ espe_ambience_list["Столовая. Полная"] = ambience_dining_hall_full
    $ espe_ambience_list["Шум у дороги. День"] = ambience_ext_road_day
    $ espe_ambience_list["Шум у дороги. Вечер"] = ambience_ext_road_evening
    $ espe_ambience_list["Шум у дороги. Ночь"] = ambience_ext_road_night
    $ espe_ambience_list["Шум в лесу. День"] = ambience_forest_day
    $ espe_ambience_list["Шум в лесу. Вечер"] = ambience_forest_evening
    $ espe_ambience_list["Шум в лесу. Ночь"] = ambience_forest_night
    $ espe_ambience_list["Кузнечики"] = ambience_grasshoper_clean
    $ espe_ambience_list["Часы в медпункте. День"] = ambience_int_cabin_day
    $ espe_ambience_list["Часы в медпункте. Вечер"] = ambience_int_cabin_evening
    $ espe_ambience_list["Часы в медпункте. Ночь"] = ambience_int_cabin_night
    $ espe_ambience_list["Река. Птицы. День"] = ambience_lake_shore_day
    $ espe_ambience_list["Река. Птицы. Вечер"] = ambience_lake_shore_evening
    $ espe_ambience_list["Река. Птицы. Ночь"] = ambience_lake_shore_night
    $ espe_ambience_list["Часы в библиотеке. День"] = ambience_library_day
    $ espe_ambience_list["Шум разговоров"] = ambience_medium_crowd_indoors_1
    $ espe_ambience_list["Шум разговоров 2"] = ambience_medium_crowd_outdoors
    $ espe_ambience_list["Часы в медпункте 2. День"] = ambience_medstation_inside_day
    $ espe_ambience_list["Часы в медпункте 2. Ночь"] = ambience_medstation_inside_night
    $ espe_ambience_list["Часы в муз. клубе. День"] = ambience_music_club_day
    $ espe_ambience_list["Часы в муз. клубе. Ночь"] = ambience_music_club_night
    $ espe_ambience_list["Около старого корпуса"] = ambience_old_camp_outside
    $ espe_ambience_list["Спортивная площадь"] = ambience_soccer_play_background
